image: cypress/internal:latest
image: node:8.4

cache:
  paths:
  - node_modules/

stages:
  - test

cypress-e2e:
  stage: test
  script:
    - cypress run
  artifacts:
    expire_in: 1 week
    paths:
    - cypress/screenshots
    - cypress/videos

development_test_and_qa:
  stage: test
  script:
   - npm install
   - ./node_modules/.bin/flow-typed install
   - npm test
   - npm run qa
   - npm run flow
